#!/bin/bash
# This script generates the keys and certificates used for testing mosquitto broker security feature.
# None of the keys are encrypted, so do not just use this script to generate
# files for your own use.
#set -x
OPTS=`getopt -o hs: --long server:,help -n 'parse-options' -- "$@"`

if [ $? != 0 ] ; then echo "Failed parsing options." >&2 ; exit 1 ; fi

#echo "$OPTS"
eval set -- "$OPTS"

HELP=false

while true; do
  case "$1" in
    -h | --help )    HELP=true; shift ;;
    -s | --server ) server_arg="$2"; shift; shift ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

help()
{

echo "./genservercert -s <mqttbroker hostname>"
echo "e.g ./genservercert -s mqttbroker"
echo "The certificates are generated in the results folder under respective hostname folders"
}

if [ $HELP = true ]; then
	help
	exit
fi

if [ -z "${server_arg// }" ] ; then
	echo "empty server name"
	exit
fi

mkdir -p results/${server_arg}

BASESUBJ="/C=GB/ST=Derbyshire/L=Derby/O=Mosquitto Project/OU=Testing"
SBASESUBJ="/C=GB/ST=Nottinghamshire/L=Nottingham/O=Server/OU=Production"

# Valid server key and certificate.
openssl genrsa -out ${server_arg}.key 1024
openssl req -new -key ${server_arg}.key -out ${server_arg}.csr -config openssl.cnf -subj "${SBASESUBJ}/CN=${server_arg}/"
yes | openssl ca -config openssl.cnf -name CA_signing -out ${server_arg}.crt -infiles ${server_arg}.csr

cp all-ca.crt ${server_arg}.key ${server_arg}.crt results/${server_arg}

#rm -rf rootCA signingCA
